label: United States regions
centroids_file: usa_regions-centroids.csv
altnames_file: usa_regions-altnames.csv
level: ADM1
regions:
id_format: "%02d"
topojson:
  scope: XXX
  geographyName: name
  geographyId: id
  path: usa_regions.topojson
projections:
  mercator:
    center: [-90.30, 16.22]
    rotate: [0, 0]
    scale: 5.5
    translate: [0,0]
  equirectangular:
    center: [-90.30, 16.22]
    rotate: [0, 0]
    scale: 5.5
    translate: [0,0]

