label: Colombia departaments
centroids_file: col-departments-centroids.csv
altnames_file: col-departments-altnames.csv
altids_file:
level: ADM1
regions_file:
id_format: "%02d"
code_cols: ["cod_dane", "codigo", "dane"]
name_cols: ["depto", "dpto", "departamento"]
topojson:
  scope: depto
  geographyName: name
  geographyId: id
  path: col-departments.topojson
projections:
  mercator:
    center: [-73.5, 4.2]
    rotate: [0, 0]
    scale: 1.8
    translate: [0,0]
  equirectangular:
    center: [-73.5, 4.2]
    rotate: [0, 0]
    scale: 1.8
    translate: [0,0]
