label: Guatemala departaments
centroids_file: gtm_departments-centroids.csv
altids_file: 
altnames_file: gtm_departments-altnames.csv
level: ADM1
regions: 
id_format: "%02d"
topojson:
  scope: XXX
  geographyName: name
  geographyId: id
  path: gtm_departments.topojson
projections:
  mercator:
    center: [-90.30, 16.22]
    rotate: [0, 0]
    scale: 5.5
    translate: [0,0]
  equirectangular:
    center: [-90.30, 16.22]
    rotate: [0, 0]
    scale: 5.5
    translate: [0,0]

