label: Colombia municipalities
centroids_file: col-adm2-municipalities-centroids.csv
altnames_file: col-adm2-municipalities-altnames.csv
altids_file:
level: ADM2
id_format: "%05d"
regions_file: col-adm2-municipalities-regions.csv
parent_map_name: col_departments
id_format: "%05d"
topojson:
  scope: mpio
  geographyName: name
  geographyId: id
  path: col-adm2-municipalities.topojson
projections:
  mercator:
    name: mercator
    center: [-73.5, 4.2]
    rotate: [0, 0]
    scale: 1.8
    translate: [0,0]
  equirectangular:
    name: mercator
    center: [-73.5, 4.2]
    rotate: [0, 0]
    scale: 1.8
    translate: [0,0]
