label: United States states
centroids_file: usa_states-centroids.csv
altnames_file: usa_states-altnames.csv
level: ADM1
regions:
id_format: "%02d"
topojson:
  scope: XXX
  geographyName: name
  geographyId: id
  path: usa_states.topojson
projections:
  mercator:
    center: [-90.30, 16.22]
    rotate: [0, 0]
    scale: 5.5
    translate: [0,0]
  equirectangular:
    center: [-90.30, 16.22]
    rotate: [0, 0]
    scale: 5.5
    translate: [0,0]

